travel: "https://app.hlas.com.sg/travel-protect360/quote"
maid: "https://app.hlas.com.sg/maid-protect360-pro/quote"
car: "https://app.hlas.com.sg/car-protect360/quote/get-started"
personalaccident: "https://app.hlas.com.sg/family-protect360/quote"
home: "https://www.hlas.com.sg/personal-insurance/home-protect360/"
early: "https://app.hlas.com.sg/early-protect360-plus"
fraud: "https://app.hlas.com.sg/fraud-protect360-plus/quote"
hospital: "https://app.hlas.com.sg/hospital-protect360/quote"
